### ISSUE TITLE
Error on exit

### ISSUE THREAD

**Issue by peileppe** [AineeJames/ChatGPTerminator#1]
Hello, 

I was playing with the program and ended with 'q'

and on exit the program generated this error:

> openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 4107 tokens. Please reduce the length of the messages.

**Comment by AineeJames** [comment]
Hmm, that is strange. Whenever you type q or exit the program should terminate right then and there, before querying the API again. I will look into this issue!

**Comment by AineeJames** [comment]
Gotchya, can I consider this issue closed?
