### ISSUE TITLE
Add support for kitty icat image preview

### ISSUE THREAD

**Issue by RexAckermann** [AineeJames/ChatGPTerminator#10]
Kitty terminal provides image preview fucttion which is ...well a bit more high res than the current one.So maybe an option to get it would be nice.

**Comment by AineeJames** [comment]
Since my goal is to make GPTerminal as portable as possible, it doesn't make much sense for me to add this functionality since it may not work for most terminals, though I am open to suggestions for another solution to the low resolution previews!
