### ISSUE TITLE
Feature Request: Add Command to Start New ChatGPT Session

### ISSUE THREAD

**Issue by wangw469** [AineeJames/ChatGPTerminator#15]
Hi there!

I'm a user of the ChatGPTerminator tool and I've been really impressed with its capabilities so far. However, I've found myself wishing there was a way to start a new ChatGPT session without having to exit the program and start it again.

I was hoping that you might consider adding a new command to the tool that would allow users to easily start a new ChatGPT session within the same program instance.

This could be as simple as adding a command like `!start-new-session` that would clear the current conversation buffer and start a new session with fresh context.

I think this would be a really helpful addition to the tool and would greatly streamline the workflow for users who want to have multiple conversations without having to constantly restart the program.

Thank you for your consideration!

**Comment by AineeJames** [comment]
You can now use the `!new` cmd or `!n` to acheive this, great suggestion!

**Comment by AineeJames** [comment]
I will be including this in the next release, for now please install by cloning the repo and running `pip install .`

**Comment by wangw469** [comment]
Thanks a lot!
