### ISSUE TITLE
Input text length is limited to a number of characters

### ISSUE THREAD

**Issue by othmanelhoufi** [AineeJames/ChatGPTerminator#16]
Hi all,

Thanks for this great tool.
I am trying to create some GPT-4 demos but I noticed that when I copy/paste my inout text with length of 4550 characters a big part of gets deleted in the console and only the end stays.
Is it a console behaviour or gpterminator limitation?

**Comment by AineeJames** [comment]
This could be either one, is there any way for you to check the maximum pasted characters that your terminal allows?
