### ISSUE TITLE
API  Key issue

### ISSUE THREAD

**Issue by alainlankers** [AineeJames/ChatGPTerminator#2]
I registered an API Key and exported the API key with the command provided. Still when I start the program I get this error: 

ERROR: Please provide an OPENAI_API_KEY evn varible
                                                                                                    
 export OPENAI_API_KEY=<place api key here>

**Comment by AineeJames** [comment]
What OS are you using?

**Comment by alainlankers** [comment]
Hello my OS is Debian 11.

**Comment by AineeJames** [comment]
If you run the following command:
```bash
echo $OPENAI_API_KEY
```
Does it print out your API key?
It's possible it isn't being set correctly.
