### ISSUE TITLE
The chatgptterminator crashed because of too many requests

### ISSUE THREAD

**Issue by peileppe** [AineeJames/ChatGPTerminator#3]
> openai.error.RateLimitError: That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 691f1c704cab28dd0835be85e87578e3 in your message.)

**Comment by AineeJames** [comment]
Ah shoot, still gotta implement some basic error catching. Unfortunately everyone wants to use the cool AI lol

**Comment by AineeJames** [comment]
closing this issue since new commit has error checking
