### ISSUE TITLE
Maintained alternatives to ChatGPTerminator

### ISSUE THREAD

**Issue by Simatwa** [AineeJames/ChatGPTerminator#31]
**ChatGPTerminator** was and is still serve the purpose so well. The only drawback is that most of the issues raised here are left unattended. 
There are multiple projects that can actually get the same work done, similar to it or even much better depending on what you concern the most.

| Project | Info |
|--------------|--------|
| [GPT-CLI](https://github.com/Simatwa/GPT-CLI) | Unites **Bard** and **ChatGPT** in  your console disposal |
[WebChatGPT](https://github.com/Simatwa/WebChatGPT) | Brings ChatGPT's web-version in your console. *(No API key required)* |
| [Python-tgpt](https://github.com/Simatwa/python-tgpt) | Access multiple LLMs from **50+ providers** right from your terminal. *No API key required.* Just installation and you're good to go. |

> **Note** : These projects are actively maintained and any concern raised will be addressed within no time.

![WebChatGPT Console Demo](https://github.com/Simatwa/WebChatGPT/blob/main/assets/demo.gif?raw=True)

**Comment by AineeJames** [comment]
bruh

**Comment by AineeJames** [comment]
bruh

**Comment by Simatwa** [comment]
> bruh

What's up folk?
