### ISSUE TITLE
Suggestion: Create a PyPi ChatGPTerminator package

### ISSUE THREAD

**Issue by Nanobot567** [AineeJames/ChatGPTerminator#4]
This would make it a lot easier for users to install ChatGPTerminator.

**Comment by AineeJames** [comment]
I completely agree, however, I have little practice with packaging projects and am hesitant due to the config file the program uses... Any ideas?

**Comment by Nanobot567** [comment]
Any ideas for how to package ChatGPTerminator, do you mean? Also, what's wrong with your config file? It looks alright to me

**Comment by AineeJames** [comment]
I figured it out I think and you should now be able to install by cloning the repo, and then running 'pip install .' Then you can call the program from anywhere with the gpterm cmd.

**Comment by Nanobot567** [comment]
Awesome! Do you think you could upload it to pypi too so users could download it directly from pip instead of cloning the repo?

**Comment by AineeJames** [comment]
You should be able to download it as of the new release using 'pip install gpterminator'! Then you can call it from anywhere by typing 'gpterm'.

**Comment by Nanobot567** [comment]
Cool, thanks for doing that! :)
