### ISSUE TITLE
exit with 'q'

### ISSUE THREAD

**Issue by Zeioth** [AineeJames/ChatGPTerminator#9]
Additionally to the '!quit' command, it would be nice to just exit with 'q', in a vim-like fashion.

This improves usability in case where the user spawn a termimal with gpterm, search something, and inmediatelly exits.
Which often is a repetitive operation.

**Comment by AineeJames** [comment]
This is a good suggestion! With the current way commands are setup, the closest i could get with the current setup would be !q. Would this be good?

**Comment by AineeJames** [comment]
Some short versions of the commands could definitely be useful!

**Comment by Zeioth** [comment]
I personally prefer 'q' but because it is easier to type. But if you like the '!' notation, !q is still much better yes.

**Comment by AineeJames** [comment]
Just released a new version w/ shorthand notations for just about all the commands. You can now quit with `!q` and is mucj faster, great suggestion!
